server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Knife4j与Spring Boot 2.6+兼容性问题
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingyu_eyes?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # Druid 数据源配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.qing.entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true
alioss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key-id: LTAI5tDFi3Yg1GAEj9PVMbbt
  access-key-secret: CBJvXMcGoahUUAfEMMqe0KvyU6y6hZ
  bucket-name: alibucket-050706
logging:
  level:
    com:
      example:
        qing:  # ?????????
          mapper: debug
          service: info
          controller: info